Matrix Creation and Manipulation
Create various types of matrices (zero matrix, identity matrix, random matrix).
Perform basic matrix operations (addition, subtraction, multiplication).
Transpose a matrix and find the determinant and inverse of a matrix.


In [25]:
import numpy as np
zeromatrix=np.zeros((2,2))
print(zeromatrix,"\n")

identity_matrix=np.eye(3,3)
print(identity_matrix,"\n")

randommatrix=np.random.randint(10,20,size=(3,3))
print(randommatrix)

[[0. 0.]
 [0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[18 16 13]
 [16 16 12]
 [13 11 17]]


In [33]:
#addition,subtraction,multiplication using identity and random matrix
addition=np.add(identity_matrix,randommatrix)
print("addition\n",addition,"\n")

subtraction=np.subtract(identity_matrix,randommatrix)
print("subtration\n",subtraction,"\n")

multiplication=np.multiply(identity_matrix,randommatrix)
print("multiplication\n",multiplication)

addition
 [[19. 16. 13.]
 [16. 17. 12.]
 [13. 11. 18.]] 

subtration
 [[-17. -16. -13.]
 [-16. -15. -12.]
 [-13. -11. -16.]] 

multiplication
 [[18.  0.  0.]
 [ 0. 16.  0.]
 [ 0.  0. 17.]]


In [39]:
#Transpose a matrix and find the determinant and inverse of a matrix.

print("transpose of matrix addition\n",np.transpose(addition),"\n")

transpose of matrix addition
 [[19. 16. 13.]
 [16. 17. 11.]
 [13. 12. 18.]] 



In [42]:

print("determinant of matric multiplication\n",np.linalg.det(multiplication),"\n")

print("inverse of identity matrix is also an identity matrix\n",np.linalg.inv(identity_matrix))

determinant of matric multiplication
 4896.000000000001 

inverse of identity matrix is also an identity matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Solving Linear Equations:
Using NumPy to solve a system of linear equations.


In [50]:
#let us suppose we have 3 linear equations 
#x + 2y + z = 5 , 2x + y + 3z = 6 ,x + 3y + 2z = 7
#then the system of linear equation will be x=BA^-1
#here B is the column matrix of zeros 1*3 and A is 3*3 matrix of co-efficients
A=np.array([[5,2,1],[2,1,3],[4,3,5]])
B=np.array([5,6,7])
#solving the equation
sol=np.linalg.solve(A,B)
print("values of x,y and z are :",sol)

values of x,y and z are : [ 1.92857143 -3.21428571  1.78571429]


In [70]:
#implementing matrix factorization methods (LU decomposition, QR decomposition).
#LU decomposition
from scipy.linalg import lu
per,low,upp=lu(A)
print("upper triangular matrix of A is \n",upp)
print("\nlower triangular matrix of A is \n",low)
print("\n permuation matrix of A is\n ",per)
print("\n dot product of upper and lower triangular matrix \n",np.dot(low,upp))

upper triangular matrix of A is 
 [[5.  2.  1. ]
 [0.  1.4 4.2]
 [0.  0.  2. ]]

lower triangular matrix of A is 
 [[1.         0.         0.        ]
 [0.8        1.         0.        ]
 [0.4        0.14285714 1.        ]]

 permuation matrix of A is
  [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

 dot product of upper and lower triangular matrix 
 [[5. 2. 1.]
 [4. 3. 5.]
 [2. 1. 3.]]


In [68]:
#QR decomposition
q,r=np.linalg.qr(A)
print("orthogonal matrix of A is \n",q)
print("\nupper triangular matrix of A is \n",r)
print("\n dot product of upper and lower triangular matrix \n",np.dot(q,r))

orthogonal matrix of A is 
 [[-0.74535599  0.60858062  0.27216553]
 [-0.2981424   0.06085806 -0.95257934]
 [-0.59628479 -0.79115481  0.13608276]]

upper triangular matrix of A is 
 [[-6.70820393 -3.57770876 -4.62120715]
 [ 0.         -1.09544512 -3.16461922]
 [ 0.          0.         -1.90515869]]

 dot product of upper and lower triangular matrix 
 [[5. 2. 1.]
 [2. 1. 3.]
 [4. 3. 5.]]


Eigenvalues and Eigenvectors:Calculate the eigenvalues and eigenvectors of a given matrix.

In [74]:
eigenvalues,eigenvectors=np.linalg.eig(A)
print("eigen values of matrix A are:",eigenvalues)
print("\neigen vector of matrix A is \n",eigenvectors)

eigen values of matrix A are: [ 8.76382033  2.80557368 -0.56939401]

eigen vector of matrix A is 
 [[ 0.43476441  0.64748117  0.27560581]
 [ 0.41984377 -0.38018818 -0.91492234]
 [ 0.79668759 -0.66047337  0.29488734]]


In [79]:
#Verify the results by reconstructing the original matrix.
#A=CDC^-1, here C is the matrix whose columns are the eigen vectors of A
#D is the diagonal matrix with eigen values of A
inv=np.linalg.inv(eigenvectors)
temp=np.dot(eigenvectors,np.diag(eigenvalues))
final=np.dot(temp,inv)
print(final)

[[5. 2. 1.]
 [2. 1. 3.]
 [4. 3. 5.]]


In [88]:
#Matrix Decomposition: Understand and implement Principal Component Analysis (PCA) using SVD
#pca finds new set of orthogonal axes with maximum variance, svd decomposes 
#vectors into singular vectors which are related to pca.
meanA=np.mean(A)
centerA=A-meanA
#computing the co-variance matrix
covmA=np.cov(centerA)
a,b,c=np.linalg.svd(covmA)
k=3
reduce=a[:,:k]
reduced=np.dot(centerA,reduce)
reduced

array([[-2.56177919,  1.32366998, -0.70710678],
       [ 0.51784189,  1.44990005,  1.41421356],
       [-0.64730236, -1.81237506,  1.41421356]])