numpy is a machine learning library which help to perform differnt mathmatical operations

In [1]:
import numpy as np

In [4]:
#arranging a numpy array from 0 to 9
arr=np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
for i in range(len(arr)):
  print(arr[i])
print(type(arr))


0
1
2
3
4
5
6
7
8
9
<class 'numpy.ndarray'>


In [6]:
#printing numpy array having only zeros and length is 10
arr1=np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#printing array of ones of size 10
arr2=np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
arr1+arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
arr3=np.random.randint(1,20,size=10)
arr3

array([ 1, 14,  8, 12,  6, 13,  7, 14, 12,  7])

In [10]:
arr4=np.random.rand(10)
arr4

array([0.23215179, 0.09695592, 0.60256502, 0.04129291, 0.04730568,
       0.90977564, 0.26259623, 0.36639504, 0.0367398 , 0.00978564])

In [11]:
#numpy operations
sum=np.add(arr3,arr4)
sum

array([ 1.23215179, 14.09695592,  8.60256502, 12.04129291,  6.04730568,
       13.90977564,  7.26259623, 14.36639504, 12.0367398 ,  7.00978564])

In [12]:
prod=np.multiply(arr3,arr4)
prod

array([ 0.23215179,  1.35738291,  4.82052019,  0.49551488,  0.28383407,
       11.82708335,  1.83817364,  5.12953057,  0.44087764,  0.06849947])

In [13]:
a1=np.random.randint(1,10,size=4)
a2=np.random.randint(1,10,size=4)
print(a1)
print(a2)
prod=np.dot(a1,a2)
prod

[2 2 1 1]
[7 1 5 4]


25

In [14]:
a3=np.random.randint(1,10,size=10)
a3

array([9, 5, 8, 2, 2, 2, 9, 1, 9, 7])

In [15]:
print(np.min(a3))
print(np.max(a3))
print(np.mean(a3))

1
9
5.4


In [16]:
print(np.random.normal(0,1,10))

[ 0.3528081  -0.3435067  -0.82176231 -0.92745706 -2.0767975   0.23030449
  0.43817799  0.1006055  -0.16089675  1.26390352]


In [17]:
a1=np.random.randint(1,10,size=2)#2 by 1
a2=np.random.randint(1,10,size=(2,2))#2 by 2
print(a1)
print(a2)

[2 9]
[[1 5]
 [4 6]]


In [18]:
print(np.dot(a1,a2))

[38 64]


In [19]:
a1=np.random.randint(1,10,size=(3,3))

In [20]:
type(a1)

numpy.ndarray

In [21]:
np.bincount(np.random.randint(1,7,size=1000))[1:]

array([167, 168, 155, 161, 187, 162], dtype=int64)

In [22]:
a1=np.array([2,4,6,8,10])
print(np.mean(a1))
print(np.median(a1))

6.0
6.0
