logistic regression works for two cases only either ture or false, spam or not
 but what if we have to decide among more than 2 classes, like if we have to decide 
 either mail is urgent,normal or unneccessary, for more than 2 classes logistic regression will
 not work so we came with a new idea called softmax regression  also known as 
mutli nomial regression       
mathmatical version of softmax is sigma(z1)=sigma(z1)/sigma(z1)+sigma(z2)+sigma(z3), this value in the form of probability. 
there is a threshold for each class. if softmax value falls in the threshold then that will be the class of input.

In [81]:
import pandas as pd
import numpy as np
#making own random data set of diabetes
ages=np.random.randint(20,80,size=100)
bp=np.random.randint(80.0,180.0,size=100)
chl=np.random.randint(150,300,size=100)
types=np.random.choice([1,2,3],size=100)
df=pd.DataFrame({'age':ages,'cholesterol level':chl,'blood pressure':bp,'type':types})
df.tail(5)

age  cholesterol level  blood pressure  type
95   59                170              94     2
96   70                203             178     1
97   61                252             131     2
98   26                208             148     1
99   69                221              84     1

In [82]:
x=df.iloc[:,0:3]
y=df.iloc[:,-1]

In [83]:
from sklearn.model_selection import train_test_split
trainx,testx,trainy,testy=train_test_split(x,y,test_size=0.20,random_state=21)

In [84]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
trainx=scaler.fit_transform(trainx)
testx=scaler.transform(testx)

In [85]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression(multi_class='multinomial')
log.fit(trainx,trainy)
predicty=log.predict(testx)
predicty

array([3, 2, 3, 3, 3, 2, 2, 3, 3, 2, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3])

In [86]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("accuracy of mode is {:.2f}%".format(accuracy_score(testy,predicty)*100))
print("confusion matrix \n",confusion_matrix(testy,predicty))
print("classification report \n",classification_report(testy,predicty))

accuracy of mode is 30.00%
confusion matrix 
 [[0 2 8]
 [0 1 1]
 [0 3 5]]
classification report 
               precision    recall  f1-score   support

           1       0.00      0.00      0.00        10
           2       0.17      0.50      0.25         2
           3       0.36      0.62      0.45         8

    accuracy                           0.30        20
   macro avg       0.17      0.38      0.23        20
weighted avg       0.16      0.30      0.21        20



C:\Users\PMLS\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PMLS\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PMLS\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [87]:
def predict():
    age=int(input("enter your age:"))
    chl=int(input("enter your choleterol level:"))
    bp=int(input("enter your blood pressure value:"))
    arr=np.array([[age,chl,bp]])
    predict=log.predict(arr)
    if predict==3:
        print("you have diabetes type 3")
    elif predict==2:
        print("you have diabetes type 2")
    else:
        print("you have diabetes type 1")

In [88]:
predict()

enter your age: 20
enter your choleterol level: 180
enter your blood pressure value: 80


you have diabetes type 2
